
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '57B3114BA1522D5B431B8565769EFD34'
    
_lr_action_items = {'AND':([3,6,13,17,18,19,20,],[-4,9,-5,-6,-1,-3,-2,]),'INFERENCE':([3,6,13,17,18,19,20,],[-4,10,-5,-6,-1,-3,-2,]),'STRING':([0,4,5,7,9,10,11,],[1,1,8,1,1,1,1,]),'NEG':([4,],[7,]),'LPAREN':([0,1,4,7,9,10,11,],[4,5,4,4,4,4,4,]),'RPAREN':([3,8,12,13,14,15,16,17,18,19,20,],[-4,13,17,-5,18,19,20,-6,-1,-3,-2,]),'OR':([3,6,13,17,18,19,20,],[-4,11,-5,-6,-1,-3,-2,]),'$end':([2,3,13,17,18,19,20,],[0,-4,-5,-6,-1,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ATOMIC_SENTENCE':([0,4,7,9,10,11,],[3,3,3,3,3,3,]),'SENTENCE':([0,4,7,9,10,11,],[2,6,12,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> SENTENCE","S'",1,None,None,None),
  ('SENTENCE -> LPAREN SENTENCE AND SENTENCE RPAREN','SENTENCE',5,'p_SENTENCE','parser.py',34),
  ('SENTENCE -> LPAREN SENTENCE OR SENTENCE RPAREN','SENTENCE',5,'p_SENTENCE','parser.py',35),
  ('SENTENCE -> LPAREN SENTENCE INFERENCE SENTENCE RPAREN','SENTENCE',5,'p_SENTENCE','parser.py',36),
  ('SENTENCE -> ATOMIC_SENTENCE','SENTENCE',1,'p_SENTENCE','parser.py',37),
  ('ATOMIC_SENTENCE -> STRING LPAREN STRING RPAREN','ATOMIC_SENTENCE',4,'p_ATOMIC_SENTENCE','parser.py',47),
  ('SENTENCE -> LPAREN NEG SENTENCE RPAREN','SENTENCE',4,'p_NEGATED_SENTENCE','parser.py',52),
]
